### PR TITLE
Fix unit tests with -race for collector and intermediate process

### LINKED ISSUE #90: Failures when the unit tests are run with race flag
Changed the test-unit target in Makefile to run with race flag: "$(GO) test -race ./..."

There are quite a few data race failures!! Logs are below.

I1126 06:25:16.101098   63379 udp.go:80] Collecting process from 127.0.0.1:52940 has stopped.
I1126 06:25:18.099195   63379 process.go:262] Template with id 256, and obsDomainID 1 is expired.

WARNING: DATA RACE
Write at 0x00c000115c20 by goroutine 63:
  runtime.mapdelete()
      /usr/local/go/src/runtime/map.go:685 +0x0
  github.com/vmware/go-ipfix/pkg/collector.(*CollectingProcess).deleteTemplate()
      /Users/stati/work/antrea_all/go-ipfix/pkg/collector/process.go:282 +0x138
  github.com/vmware/go-ipfix/pkg/collector.(*CollectingProcess).addTemplate.func1()
      /Users/stati/work/antrea_all/go-ipfix/pkg/collector/process.go:263 +0x214

Previous read at 0x00c000115c20 by goroutine 57:
  runtime.mapaccess1()
      /usr/local/go/src/runtime/map.go:394 +0x0
  github.com/vmware/go-ipfix/pkg/collector.TestUDPCollectingProcess_TemplateExpire()
      /Users/stati/work/antrea_all/go-ipfix/pkg/collector/process_test.go:367 +0x2d0
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:1123 +0x202

Goroutine 63 (running) created at:
  github.com/vmware/go-ipfix/pkg/collector.(*CollectingProcess).addTemplate()
      /Users/stati/work/antrea_all/go-ipfix/pkg/collector/process.go:257 +0x44e
  github.com/vmware/go-ipfix/pkg/collector.(*CollectingProcess).decodeTemplateSet()
      /Users/stati/work/antrea_all/go-ipfix/pkg/collector/process.go:207 +0xc11
  github.com/vmware/go-ipfix/pkg/collector.(*CollectingProcess).decodePacket()
      /Users/stati/work/antrea_all/go-ipfix/pkg/collector/process.go:130 +0x404
  github.com/vmware/go-ipfix/pkg/collector.(*CollectingProcess).handleUDPClient.func1()
      /Users/stati/work/antrea_all/go-ipfix/pkg/collector/udp.go:88 +0x2c7

Goroutine 57 (running) created at:
  testing.(*T).Run()
      /usr/local/go/src/testing/testing.go:1168 +0x5bb
  testing.runTests.func1()
      /usr/local/go/src/testing/testing.go:1439 +0xa6
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:1123 +0x202
  testing.runTests()
      /usr/local/go/src/testing/testing.go:1437 +0x612
  testing.(*M).Run()
      /usr/local/go/src/testing/testing.go:1345 +0x3b3
  main.main()
      _testmain.go:111 +0x356

--- FAIL: TestUDPCollectingProcess_TemplateExpire (15.01s)
    testing.go:1038: race detected during execution of test
FAIL
coverage: 87.6% of statements
FAIL	github.com/vmware/go-ipfix/pkg/collector	42.291s
ok  	github.com/vmware/go-ipfix/pkg/entities	1.781s	coverage: 69.7% of statements
?   	github.com/vmware/go-ipfix/pkg/entities/testing	[no test files]

WARNING: DATA RACE
Read at 0x00c000113168 by goroutine 12:
  github.com/vmware/go-ipfix/pkg/intermediate.(*AggregationProcess).Stop()
      /Users/stati/work/antrea_all/go-ipfix/pkg/intermediate/aggregate.go:71 +0x8a
  github.com/vmware/go-ipfix/pkg/intermediate.TestAggregationProcess.func1()
      /Users/stati/work/antrea_all/go-ipfix/pkg/intermediate/aggregate_test.go:207 +0x97

Previous write at 0x00c000113168 by goroutine 11:
  github.com/vmware/go-ipfix/pkg/intermediate.(*AggregationProcess).Start()
      /Users/stati/work/antrea_all/go-ipfix/pkg/intermediate/aggregate.go:65 +0x2b1
  github.com/vmware/go-ipfix/pkg/intermediate.TestAggregationProcess()
      /Users/stati/work/antrea_all/go-ipfix/pkg/intermediate/aggregate_test.go:211 +0x11e
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:1123 +0x202

Goroutine 12 (running) created at:
  github.com/vmware/go-ipfix/pkg/intermediate.TestAggregationProcess()
      /Users/stati/work/antrea_all/go-ipfix/pkg/intermediate/aggregate_test.go:203 +0x10d
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:1123 +0x202

Goroutine 11 (running) created at:
  testing.(*T).Run()
      /usr/local/go/src/testing/testing.go:1168 +0x5bb
  testing.runTests.func1()
      /usr/local/go/src/testing/testing.go:1439 +0xa6
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:1123 +0x202
  testing.runTests()
      /usr/local/go/src/testing/testing.go:1437 +0x612
  testing.(*M).Run()
      /usr/local/go/src/testing/testing.go:1345 +0x3b3
  main.main()
      _testmain.go:105 +0x356
--- FAIL: TestAggregationProcess (0.00s)
    testing.go:1038: race detected during execution of test
FAIL
coverage: 80.3% of statements
FAIL	github.com/vmware/go-ipfix/pkg/intermediate	0.468s
ok  	github.com/vmware/go-ipfix/pkg/producer	2.036s	coverage: 72.9% of statements
?   	github.com/vmware/go-ipfix/pkg/producer/protobuf	[no test files]
ok  	github.com/vmware/go-ipfix/pkg/registry	1.537s	coverage: 99.4% of statements
?   	github.com/vmware/go-ipfix/pkg/util	[no test files]

pkg/intermediate, pkg/collector, and pkg/exporter have failures. 

We should fix these with priority and turn on the race flag when unit tests are run.

I can take a crack at pkg/exporter. @zyiou could you look into pkg/collector failures?

### PR DESCRIPTION
**Pull request by zyiou**
Cherry-picked unit tests fixes for exporter from #91 
Fixed with collector and intermediate process and added `-race` in unit tests to check for race conditions.
partially fixes #90

### CODE REVIEW

File: pkg/collector/process_test.go [hunk 1]
```diff
@@ -57,19 +56,19 @@ func TestTCPCollectingProcess_ReceiveTemplateRecord(t *testing.T) {
...
-		cp.Stop()
+		go cp.Start()
+		for range cp.GetMsgChan() {
+			messageReceived <- true
+		}
 	}()
-	cp.Start()
-	assert.NotNil(t, cp.templatesMap[1], "TCP Collecting Process should receive and store the received template.")
-	assert.Equal(t, 1, messageCount, "Messages should be stored correctly.")
+	time.Sleep(4 * time.Second)
```
Comment (srikartati) [inline pkg/collector/process_test.go:67]: do we need this? Could we wait on messageReceived channel and close the collector process?

File: pkg/collector/process_test.go [hunk 2]
```diff
@@ -94,27 +92,26 @@ func TestUDPCollectingProcess_ReceiveTemplateRecord(t *testing.T) {
...
-		cp.Stop()
+		go cp.Start()
+		for range cp.GetMsgChan() {
+			messageReceived <- true
+		}
 	}()
-	cp.Start()
-	assert.NotNil(t, cp.templatesMap[1], "UDP Collecting Process should receive and store the received template.")
-	assert.Equal(t, 1, messageCount, "Messages should be stored correctly.")
+	time.Sleep(4 * time.Second)
```
Comment (srikartati) [inline pkg/collector/process_test.go:103]: same here.

File: pkg/collector/process_test.go [hunk 3]
```diff
@@ -360,7 +356,11 @@ func TestUDPCollectingProcess_TemplateExpire(t *testing.T) {
 		cp.Stop()
 	}()
 	cp.Start()
-	assert.NotNil(t, cp.templatesMap[1][256], "Template should be stored in the template map.")
+	template, err := cp.getTemplate(1, 256)
+	assert.NotNil(t, template, "Template should be stored in the template map.")
+	assert.Nil(t, err, "Template should be stored in the template map.")
 	time.Sleep(10 * time.Second)
```
Comment (srikartati) [inline pkg/collector/process_test.go:362]: do we need that much sleep? Collector unit tests are taking more time to run. Just want to make sure that delay is justified and a must required. If not, we can decrease the run time of tests.

File: pkg/intermediate/aggregate.go [hunk 4]
```diff
@@ -59,18 +59,22 @@ func InitAggregationProcess(messageChan chan *entities.Message, workerNum int, c
 }
 
 func (a *AggregationProcess) Start() {
+	a.mutex.Lock()
 	for i := 0; i < a.workerNum; i++ {
 		w := createWorker(i, a.messageChan, a.AggregateMsgByFlowKey)
 		w.start()
 		a.workerList = append(a.workerList, w)
 	}
+	a.mutex.Unlock()
```
Comment (srikartati) [inline pkg/intermediate/aggregate.go:68]: is there an issue using defer unlock?

Comment (zyiou) [reply pkg/intermediate/aggregate.go:68]: Since the stopChan will keep waiting for stop signal, using defer will not release the lock until stopChan receives stop signal.

File: pkg/collector/process_test.go (hunk 3 above)
Comment (zyiou) [reply pkg/collector/process_test.go:362]: Makes sense. I will only keep the necessary sleep (e.g. wait for collector ready, wait for template expiring). Thanks!

File: pkg/collector/process_test.go [hunk 5]
```diff
@@ -64,11 +64,11 @@ func TestTCPCollectingProcess_ReceiveTemplateRecord(t *testing.T) {
 			messageReceived <- true
 		}
 	}()
-	time.Sleep(4 * time.Second)
+	isReceived := <-messageReceived
```
Comment (srikartati) [inline pkg/collector/process_test.go:67]: There is only one message right? Can't we directly use that instead of creating one again? In addition, we can get away with extra go routine and directly use `go cp.Start()`.

I see that they same format used in rest of the tests.

File: pkg/collector/process_test.go [hunk 6]
```diff
@@ -49,7 +49,7 @@ func TestTCPCollectingProcess_ReceiveTemplateRecord(t *testing.T) {
 		t.Fatalf("TCP Collecting Process does not start correctly: %v", err)
 	}
 	go func() {
-		time.Sleep(2 * time.Second)
+		time.Sleep(time.Millisecond)
```
Comment (srikartati) [inline pkg/collector/process_test.go:52]: If we start the `go cp.Start()` before this go routine for fake exporter, do we still need the sleep?

**Review by srikartati — COMMENTED** [review]
There are similar sleeps in exporter_collector_test.go.
I think it will be better if we remove those sleeps too. As the test in part is an illustration on how to use exporter and collector, it will be useful to illustrate with no sleeps.
If sleep is a must, we should use `wait.Poll` from wait go package rather than adding sleeps.

File: pkg/collector/process_test.go (hunk 6 above)
Comment (zyiou) [reply pkg/collector/process_test.go]: It is still possible to cause nil pointer problem if the collector is not ready. Changed to wait.Poll to wait for collector to be ready. Thanks!

File: pkg/collector/process_test.go [hunk 7]
```diff
@@ -366,3 +381,15 @@ func TestUDPCollectingProcess_TemplateExpire(t *testing.T) {
...
 }
+
+func waitForCollectorReady(t *testing.T, address net.Addr) {
+	checkConn := func() (bool, error) {
+		if _, err := net.Dial(address.Network(), address.String()); err != nil {
+			return false, err
+		}
+		return true, nil
+	}
+	if err := wait.Poll(time.Millisecond, time.Millisecond, checkConn); err != nil {
```
Comment (srikartati) [inline pkg/collector/process_test.go:392]: increase the poll interval to 100 milliseconds and timeout to 500 milliseconds. One millisecond is too aggressive.

File: pkg/test/collector_intermediate_test.go [hunk 8]
```diff
@@ -74,3 +71,15 @@ func copyFlowKeyRecordMap(key intermediate.FlowKey, records []entities.Record) e
...
 }
+
+func waitForCollectorReady(t *testing.T, address net.Addr) {
+	checkConn := func() (bool, error) {
+		if _, err := net.Dial(address.Network(), address.String()); err != nil {
+			return false, err
+		}
+		return true, nil
+	}
+	if err := wait.Poll(time.Millisecond, time.Millisecond, checkConn); err != nil {
```
Comment (srikartati) [inline pkg/test/collector_intermediate_test.go:82]: same here

File: pkg/test/collector_intermediate_test.go [hunk 9]
```diff
@@ -33,24 +34,20 @@ func TestCollectorToIntermediate(t *testing.T) {
...
-		time.Sleep(time.Second)
 		conn.Write(dataPacket2)
 	}()
+	go ap.Start()
 	go func() {
-		ap.Start()
-	}()
-	go func() {
-		time.Sleep(4 * time.Second)
+		time.Sleep(time.Second)
```
Comment (srikartati) [inline pkg/test/collector_intermediate_test.go:50]: is there any indicator from aggregation process that messages and records are ready? Please use that instead of sleep.

In addition you should start cp.Start in go routine wait in the test main to stop collector process and aggregation process.

File: pkg/test/exporter_collector_test.go [hunk 10]
```diff
@@ -208,7 +207,7 @@ func testExporterToCollector(address net.Addr, isMultipleRecord bool, t *testing
 			klog.Fatalf("Got error when sending record: %v", err)
 		}
 		export.CloseConnToCollector() // Close exporting process
-		time.Sleep(2 * time.Second)
+		time.Sleep(time.Second)
```
Comment (srikartati) [inline pkg/test/exporter_collector_test.go:210]: Here as well move the collector process start to go routine.
Remove the for loop over message channel from go routine and put it in test main. Once that is done, we can safely close collector process. We do not need sleep.

File: pkg/test/collector_intermediate_test.go (hunk 9 above)
Comment (zyiou) [reply pkg/test/collector_intermediate_test.go]: Updated wait with checking whether flowKeyRecordMap gets data. Thanks!

File: pkg/test/exporter_collector_test.go [hunk 11]
```diff
@@ -207,16 +210,15 @@ func testExporterToCollector(address net.Addr, isMultipleRecord bool, t *testing
...
 	}()
-	go func() {
-		for message := range cp.GetMsgChan() {
-			messages = append(messages, message)
+
+	for message := range cp.GetMsgChan() {
+		messages = append(messages, message)
+		if len(messages) == 2 {
+			break
 		}
```
Comment (srikartati) [inline pkg/test/exporter_collector_test.go:219]: Nit: We could close the msgChan is export go routine after L212 (export.CloseConnToCollector()), instead of having this logic. Feel this is more elegant.

Comment (zyiou) [reply pkg/test/exporter_collector_test.go:219]: makes sense. if we close the msgChan directly after exporter exports message, the messages may not be processed and taken out from the channel. instead I put the channel closing after we get two messages. Thanks!

**Review by srikartati — APPROVED** [review]
Thanks for making changes.
