### PR TITLE
Fix testing problems for TestCollectorToIntermediate and golangci-lint

### LINKED ISSUE #109: TestCollectorToIntermediate is flaky
**Describe the bug**
TestCollectorToIntermediate is flaky. It is not passing consistently. Example run: https://github.com/vmware/go-ipfix/runs/1539468529

**To Reproduce**
Run the test locally with count=50. 

**Expected behavior**
Test should pass consistently.

**Actual Behavior**
I1211 19:59:29.646039    4907 tcp.go:38] Start tcp collecting process on [::]:4739
I1211 19:59:29.749036    4907 tcp.go:73] Connection from 127.0.0.1:49328 has been closed.
--- FAIL: TestCollectorToIntermediate (0.21s)
    collector_intermediate_test.go:167: 
        	Error Trace:	collector_intermediate_test.go:167
        	Error:      	Not equal: 
        	            	expected: 0x190
        	            	actual  : 0x3e8
        	Test:       	TestCollectorToIntermediate
    collector_intermediate_test.go:177: 
        	Error Trace:	collector_intermediate_test.go:177
        	Error:      	Not equal: 
        	            	expected: 0x3e8
        	            	actual  : 0x190
        	Test:       	TestCollectorToIntermediate

**Versions**
ToT master branch

### LINKED ISSUE #119: Github Actions Golangci-lint is not working correctly
**Describe the bug**
Golangci-lint is passed automatically even though there is error in `make golangci-lint`.

**To Reproduce**
run `make golangci-lint` locally with some error logs. when pushing the code, the workflow will pass.
Here is an [example](https://github.com/vmware/go-ipfix/runs/1561102825?check_suite_focus=true) run.

**Expected behavior**
workflow should not pass when there are errors in golangci-lint and marked workflow as failed.

**Actual Behavior**
Golangci-lint workflow passed.

**Versions**
master branch

**Additional context**

### PR DESCRIPTION
**Pull request by zyiou**
fixes #109 
fixes #119

### CODE REVIEW

File: pkg/intermediate/aggregate.go [hunk 1]
```diff
@@ -304,7 +309,13 @@ func (a *AggregationProcess) aggregateRecords(incomingRecord, existingRecord ent
 			}
 			// Update the corresponding source element in antreaStatsElement list.
 			if fillSrcStats {
-				existingIeWithValue, _ := existingRecord.GetInfoElementWithValue(antreaSourceStatsElements[i])
+				name := antreaSourceStatsElements[i]
+				var existingIeWithValue *entities.InfoElementWithValue
+				if isIntraNode {
+					existingIeWithValue, _ = existingRecord.GetInfoElementWithValue(name)
+				} else {
+					existingIeWithValue, _ = existingRecord.GetInfoElementWithValue(getReverseInfoElementName(name))
```
Comment (srikartati) [inline pkg/intermediate/aggregate.go:317]: Why is this needed? In the case of inter node flows, flows in conntrack module on both nodes follow the same directions.

File: pkg/test/collector_intermediate_test.go [hunk 2]
```diff
@@ -143,6 +143,8 @@ func TestCollectorToIntermediate(t *testing.T) {
 		defer conn.Close()
 		conn.Write(templatePacket)
 		conn.Write(dataPacket1)
+		// sleep to ensure dataPacket1 is processed first so that the total count fields are using values from dataPacket1
+		time.Sleep(time.Millisecond)
```
Comment (srikartati) [inline pkg/test/collector_intermediate_test.go:147]: This is TCP connection right. Ord
er of packets should be followed. Did you get a chance to run the test with count=500 or some large number?

File: pkg/intermediate/aggregate.go (hunk 1 above)
Comment (zyiou) [reply pkg/intermediate/aggregate.go:317]: you mean that for flow record from src and flow record from dst, if they represent the same flow, they should have same `packetDeltaCount` and `packetTotalCount`? 
I was under impression that the `packetDeltaCount` in src record should be the same as `reversePacketDeltaCount` in dst record.

Comment (srikartati) [reply pkg/intermediate/aggregate.go:317]: Yup it is the same packet that is used to create conntrack flow on both nodes, so its direction is considered as original direction and the other direction is reverse direction. You should dump the conntrack flows in the case of inter-node flow scenario and see this.

File: pkg/collector/process_test.go [hunk 3]
```diff
@@ -628,14 +634,14 @@ func TestDTLSCollectingProcess(t *testing.T) {
...
 }
 
-func waitForCollectorReady(t *testing.T, address net.Addr) {
+func waitForCollectorReady(t *testing.T, cp *CollectingProcess) {
 	checkConn := func() (bool, error) {
-		if _, err := net.Dial(address.Network(), address.String()); err != nil {
+		if _, err := net.Dial(cp.GetAddress().Network(), cp.GetAddress().String()); err != nil {
 			return false, err
 		}
 		return true, nil
```
Comment (srikartati) [inline pkg/collector/process_test.go:642]: Could we close the connection before returning true, so we can check for exact connections in this line:
https://github.com/vmware/go-ipfix/pull/114/files#diff-24e923a024538e6ea8a21097adf7e88b862e14a44c743290238252e0a429d1e7R362 ?

File: pkg/collector/tcp.go [hunk 4]
```diff
@@ -47,18 +45,15 @@ func (cp *CollectingProcess) startTCPServer() {
...
 			}
-			wg.Add(1)
-			go cp.handleTCPClient(conn, &wg)
+			go cp.handleTCPClient(conn)
 		}
 	}()
 	<-cp.stopChan
 	// close all connections
 	cp.closeAllClients()
-	wg.Wait()
```
Comment (srikartati) [inline pkg/collector/tcp.go:57]: As stopChan is there, is waitGroup redundant?

File: pkg/test/collector_intermediate_test.go [hunk 5]
```diff
@@ -56,14 +56,14 @@ dataPacket 2:
 	"destinationTransportPort": 5678
 	"protocolIdentifier": 6
 	"flowEndSeconds": 1257895000
-	"packetTotalCount": 400
-	"packetDeltaCount": 200
+	"packetTotalCount": 1000
```
Comment (srikartati) [inline pkg/test/collector_intermediate_test.go:59]: why same? I know it can be similar but as they are not synchronized, they may not be exactly the same stats. 

Does the order issue with tcp still exists? I am just curious.

**Review by srikartati — COMMENTED** [review]
Thanks for taking care of go lint issue.

Why checking into release-0.4.0? Isn't master good enough?

File: pkg/collector/process_test.go (hunk 3 above)
Comment (zyiou) [reply pkg/collector/process_test.go:642]: if we close the connection, we cannot send data to corresponding connection. Do you mean we can create another function to wait for two clients shown up and close the connection?

File: pkg/collector/tcp.go (hunk 4 above)
Comment (zyiou) [reply pkg/collector/tcp.go:57]: Yes

File: pkg/test/collector_intermediate_test.go (hunk 5 above)
Comment (zyiou) [reply pkg/test/collector_intermediate_test.go]: I was just trying to simulate the condition. since they may not be exactly the same, I changed it to different values.
For order issue in tcp, it will not cause order problem in collector since data are received in order. Because aggregation has two workers, the sequence of processing will differ. I have changed the worker number to 1. It should be working now.

**Comment by zyiou** [comment]
> Why checking into release-0.4.0? Isn't master good enough?

Sorry I was using the previous setting. Changed to use master branch as base.

File: pkg/collector/process_test.go (hunk 3 above)
Comment (srikartati) [reply pkg/collector/process_test.go:642]: I was talking about the connection created in L639, which we are ignoring right now.

File: pkg/test/collector_intermediate_test.go (hunk 5 above)
Comment (srikartati) [reply pkg/test/collector_intermediate_test.go]: Processing with two workers is an important point. We should allow this either sending all flow records of an individual flow to one worker or update the flow records carefully if flow records can be processed by multiple workers.
Should we update only if the value is more than current value for Total stats?

Comment (zyiou) [reply pkg/test/collector_intermediate_test.go]: Yes it makes sense to update total stats when value is larger. Will update the code then. Thanks!

File: pkg/producer/kafka_test.go [hunk 6]
```diff
@@ -31,14 +31,14 @@ import (
...
 		0x30, 0x2e, 0x32, 0x40, 0xd2, 0x9, 0x48, 0xae, 0x2c, 0x50, 0x6, 0x58, 0xe8,
 		0x7, 0x60, 0xe8, 0x7, 0x68, 0xe8, 0x7, 0x70, 0xe8, 0x7, 0x78, 0x32, 0x80,
 		0x1, 0x32, 0x88, 0x1, 0x32, 0x90, 0x1, 0x32, 0xca, 0x1, 0xb, 0x31, 0x39,
 		0x32, 0x2e, 0x31, 0x36, 0x38, 0x2e, 0x30, 0x2e, 0x31, 0x8a, 0x2, 0x9, 0x31,
 		0x32, 0x37, 0x2e, 0x30, 0x2e, 0x30, 0x2e, 0x31, 0x90, 0x2, 0x83, 0x25}
-	msg2InBytes = []byte{0x86, 0x1, 0x10, 0x1, 0x18, 0xd2, 0x9, 0x32, 0x19, 0x32,
+	msg2InBytes = []byte{0x10, 0x1, 0x18, 0xd2, 0x9, 0x32, 0x19, 0x32,
 		0x30, 0x30, 0x31, 0x3a, 0x30, 0x3a, 0x33, 0x32, 0x33, 0x38, 0x3a, 0x64,
 		0x66, 0x65, 0x31, 0x3a, 0x36, 0x33, 0x3a, 0x3a, 0x66, 0x65, 0x66, 0x62,
 		0x3a, 0x19, 0x32, 0x30, 0x30, 0x31, 0x3a, 0x30, 0x3a, 0x33, 0x32, 0x33,
```
Comment (zyiou) [inline pkg/producer/kafka_test.go:44]: @srikartati when I changed to marshal function from `google.golang.org/protobuf/proto`, the marshal result and encoding result is a little bit different. Do you know the reason for that?

File: pkg/collector/process_test.go (hunk 3 above)
Comment (shihhaoli) [reply pkg/collector/process_test.go:642]: Just curious, should waitForCollectorReady return error if collector is not ready after 5 retries?

File: pkg/producer/kafka_test.go (hunk 6 above)
Comment (srikartati) [reply pkg/producer/kafka_test.go:44]: @zyiou Sorry for the delayed response.
The difference is because the `encodedMessage` method prefixes the message with length whereas Marshal doesn't do that. https://godoc.org/github.com/golang/protobuf/proto#Buffer.EncodeMessage

Comment (zyiou) [reply pkg/producer/kafka_test.go:44]: Got it. Do I need to prepend the length to current bytes to keep things same as before? Because `google.golang.org/protobuf/proto` does not have the exact same function as `EncodeMessage` in previous version.

Comment (srikartati) [reply pkg/producer/kafka_test.go:44]: Looked at this more closely. This depends on the Kafka decoder functionality--some seem to expect length-delimited messages and some do not. I did not consider both options in my previous PR as we have a mock consumer in tests, there was no issue. 
However, it is better to support both with an input bool option "KafkaDelimitMsgWithLen" by defining a default value.

Comment (zyiou) [reply pkg/producer/kafka_test.go:44]: Got it. Will add it in this patch since it is part of fixing for golangci-lint. Thanks!

Comment (srikartati) [reply pkg/producer/kafka_test.go]: Are you thinking of fixing this in separate PR?

Comment (zyiou) [reply pkg/producer/kafka_test.go]: Yes, when we cherry-pick the fixes from v0.4.3 to master branch, we can fix that. Since now the 0.4.0 branch does not have the Kafka commit.

Comment (srikartati) [reply pkg/producer/kafka_test.go]: sounds good.

File: pkg/collector/process_test.go (hunk 3 above)
Comment (srikartati) [reply pkg/collector/process_test.go:645]: This still seems to be outstanding. Any follow up comment on this?

Comment (zyiou) [reply pkg/collector/process_test.go]: Sorry for the late reply. @srikartati updated the close connection code, now we can check exact number of clients. @shihhaoli yes it will log error if the collector is not ready, which will cause the tests to fail.

**Review by srikartati — APPROVED** [review]
LGTM
